// Auto-generated by confect-generate - loads Confect error types automatically
  // This file should be committed to version control for other developers and CI/CD
  // Re-run 'confect-generate' if you modify your Convex functions with new error types
  /// <reference types="@monorepo/backend/confect-types" />
  
  export {}
  