packages:
  - "apps/*"
  - "packages/**/*"
catalog:
  # Effect Ecosystem
  
  'effect': 3.17.13
  '@effect/platform': 0.90.7
  '@effect/platform-node': 0.96.1
  '@effect/vitest': 0.25.1
  '@effect/experimental': 0.54.6
  '@effect/language-service': 0.38.1
  '@effect-atom/atom': 0.1.20
  '@effect-atom/atom-react': 0.1.15
  # React ecosystem
  'react': 19.0.0
  'react-dom': 19.0.0
  '@types/react': ~19.0.10
  '@types/react-dom': ^19.0.4
  # React Native ecosystem
  'nativewind': 4.1.23
  'lucide-react-native': 0.511.0
  'react-native-svg': 15.11.2
  # TanStack ecosystem
  '@tanstack/react-form': ^1.15.2
  '@tanstack/react-query': ^5.84.1
  '@tanstack/react-router': ^1.130.12
  '@tanstack/react-router-with-query': ^1.130.12
  '@tanstack/react-start': ^1.130.12
  '@tanstack/router-plugin': ^1.130.12
  '@tanstack/react-router-devtools': ^1.130.12
  '@tanstack/react-devtools': 0.2.2
  # Backend & Database
  'convex': ^1.25.4
  '@convex-dev/react-query': 0.0.0-alpha.10
  # Build tools & TypeScript
  'typescript': ~5.9.2
  'vite': 7.1.4
  '@vitejs/plugin-react': 5.0.2
  '@vitejs/plugin-react-swc': 4.0.1
  # UI & Styling
  'tailwindcss': 4.1.13
  '@tailwindcss/vite': 4.1.13
  'class-variance-authority': ^0.7.1
  'clsx': ^2.1.1
  'tailwind-merge': ^3.3.1
  'lucide-react': 0.542.0
  'next-themes': ^0.4.6
  'sonner': 2.0.7
  'tw-animate-css': 1.3.8
  'tailwindcss-animate': ^1.0.7
  # Utilities
  'zod': ^3.22.4
  'vite-tsconfig-paths': ^5.1.4
  # Testing
  '@testing-library/dom': 10.4.1
  '@testing-library/react': 16.3.0
  'jsdom': 26.1.0
  'web-vitals': 5.1.0
  'vitest': 3.0.5
onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - 'esbuild'
  - 'nx'
  - 'msgpackr-extract'
