packages:
  - apps/*
  - packages/**/*

catalog:
  # Effect Ecosystem
  
  'effect': '3.17.7'
  '@effect/platform': '0.90.1'
  '@effect/platform-node': '0.94.1'
  '@effect/vitest': '0.25.0'
  '@effect/experimental': '0.54.4'
  '@effect/language-service': '0.34.0'
  '@effect-atom/atom': '0.1.5'
  '@effect-atom/atom-react': '0.1.3'

  # React ecosystem
  'react': '19.0.0'
  'react-dom': '19.0.0'
  '@types/react': '~19.0.10'
  '@types/react-dom': '^19.0.4'

  # React Native ecosystem
  'nativewind': '4.1.23'
  'lucide-react-native': '0.511.0'
  'react-native-svg': '15.11.2'

  # TanStack ecosystem
  '@tanstack/react-form': '^1.15.2'
  '@tanstack/react-query': '^5.84.1'
  '@tanstack/react-router': '^1.130.12'
  '@tanstack/react-router-with-query': '^1.130.12'
  '@tanstack/react-start': '^1.130.12'
  '@tanstack/router-plugin': '^1.130.12'
  '@tanstack/react-router-devtools': '^1.130.12'

  # Backend & Database
  'convex': '^1.25.4'
  '@convex-dev/react-query': '0.0.0-alpha.10'

  # Build tools & TypeScript
  'typescript': '~5.9.2'
  'vite': '^7.0.6'
  '@vitejs/plugin-react': '^4.5.2'
  '@vitejs/plugin-react-swc': '^3.5.0'

  # UI & Styling
  'tailwindcss': '^4.1.3'
  '@tailwindcss/vite': '^4.1.8'
  'class-variance-authority': '^0.7.1'
  'clsx': '^2.1.1'
  'tailwind-merge': '^3.3.1'
  'lucide-react': '^0.525.0'
  'next-themes': '^0.4.6'
  'sonner': '^2.0.3'
  'tw-animate-css': '^1.2.5'
  'tailwindcss-animate': '^1.0.7'

  # Utilities
  'zod': '^3.22.4'
  'vite-tsconfig-paths': '^5.1.4'

  # Testing
  '@testing-library/dom': '^10.4.0'
  '@testing-library/react': '^16.2.0'
  'jsdom': '^26.0.0'
  'web-vitals': '^5.0.3'

onlyBuiltDependencies:
  - '@parcel/watcher'
  - '@tailwindcss/oxide'
  - 'esbuild'
  - 'nx'
  - 'msgpackr-extract'