// Auto-generated by Confect Error Types Generator
// Do not edit this file manually
// This file should be committed to version control for other developers and CI/CD
// This file is automatically loaded when you import @monorepo/confect/react/effect

import type { NotFoundError } from './convex/functions.js'

declare module '@monorepo/confect/react/effect' {
  interface ConfectErrorTypes {
    insertTodo: NotFoundError
    listTodos: NotFoundError
    deleteTodo: NotFoundError
    toggleTodo: NotFoundError
    getFirst: NotFoundError
  }
}

// biome-ignore lint/complexity/noUselessEmptyExport: <auto-generated>
export {}

// Helper types for individual functions
export type InsertTodoErrors = NotFoundError
export type ListTodosErrors = NotFoundError
export type DeleteTodoErrors = NotFoundError
export type ToggleTodoErrors = NotFoundError
export type GetFirstErrors = NotFoundError

// Auto-load this module when @monorepo/confect/react/effect is imported
declare global {
  namespace ConfectTypes {
    interface ErrorTypesLoaded {
      [key: string]: any
    }
  }
}

// This ensures the module is loaded when any part of confect is imported
export {}