// Auto-generated by Confect Error Types Generator
// Do not edit this file manually
// This file should be committed to version control for other developers and CI/CD
// This file is automatically loaded when you import @monorepo/confect/react/effect

import type { NotFoundError } from './convex/functions.js'

// Module augmentation for main react module
declare module '@monorepo/confect/react' {
  interface ConfectErrorTypes {
    "functions.insertTodo": NotFoundError
    "functions.listTodos": NotFoundError
    "functions.deleteTodo": NotFoundError
    "functions.toggleTodo": NotFoundError
    "functions.getFirst": NotFoundError
  }
}

// Module augmentation for effect-atom module
declare module '@monorepo/confect/react/effect-atom' {
  interface ConfectErrorTypes {
    "functions.insertTodo": NotFoundError
    "functions.listTodos": NotFoundError
    "functions.deleteTodo": NotFoundError
    "functions.toggleTodo": NotFoundError
    "functions.getFirst": NotFoundError
  }
}

// biome-ignore lint/complexity/noUselessEmptyExport: <auto-generated>
export {}

// Helper types for individual functions
export type FunctionsInsertTodoErrors = NotFoundError
export type FunctionsListTodosErrors = NotFoundError
export type FunctionsDeleteTodoErrors = NotFoundError
export type FunctionsToggleTodoErrors = NotFoundError
export type FunctionsGetFirstErrors = NotFoundError

// Auto-load this module when @monorepo/confect/react/effect is imported
declare global {
  namespace ConfectTypes {
    interface ErrorTypesLoaded {
      [key: string]: any
    }
  }
}

// This ensures the module is loaded when any part of confect is imported
export {}